---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.04-chef-10
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
- name: ubuntu-12.04-chef-11
  driver_config:
    box: ktc-ubuntu-12.04_chef-11.4.0
    box_url: https://dl.dropbox.com/u/848501/ktc-ubuntu-12.04_chef-11.4.0.box

suites:
- name: default
  run_list:
  - recipe[sysctl::attribute_driver]
  attributes: {
    sysctl: {
      values: {
        "net.core.rmem_default": "262144",
        "net.core.wmem_default": "262144",
        "fs.file-max": 1000000,
        "net.ipv4.tcp_fin_timeout": 30
      }
    }
  }
